birdcollector/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("main_app.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("birds/", views.birds_index, name="index"),
    # path("birds/", views.birds_index, name="birds_index"),
    path("birds/<int:bird_id>/", views.birds_detail, name="detail"),
    # path("birds/<int:bird_id>/", views.birds_detail, name="birds_detail"),
    path("birds/create/", views.BirdCreate.as_view(), name="birds_create"),
    path("birds/<int:pk>/update/", views.BirdUpdate.as_view(), name="birds_update"),
    path("birds/<int:pk>/delete/", views.BirdDelete.as_view(), name="birds_delete"),
    path("birds/<int:bird_id>/add_feeding/", views.add_feeding, name="add_feeding"),
    path("toys/", views.toys_index, name="toys_index"),
    path("toys/<int:toy_id>/", views.toys_detail, name="toys_detail"),
    path("toys/create/", views.ToyCreate.as_view(), name="toys_create"),
    path("toys/<int:pk>/update/", views.ToyUpdate.as_view(), name="toys_update"),
    path("toys/<int:pk>/delete/", views.ToyDelete.as_view(), name="toys_delete"),
    path(
        "birds/<int:bird_id>/assoc_toy/<int:toy_id>/", views.assoc_toy, name="assoc_toy"
    ),
    path("birds/<int:bird_id>/add_photo", views.add_photo, name="add_photo"),
    path("accounts/signup/", views.signup, name="signup"),
    path(
        "birds/<int:bird_id>/unassoc_toy/<int:toy_id>/",
        views.unassoc_toy,
        name="unassoc_toy",
    ),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

# import the built-in User model from django library
from django.contrib.auth.models import User

# Create your models here.

MEALS = (("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner"))


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("toys_detail", kwargs={"toy_id": self.id})
        # return reverse("toys_detail", kwargs={"pk": self.id})

    class Meta:
        ordering = ["name"]


class Bird(models.Model):
    name = models.CharField(max_length=250)
    breed = models.CharField(max_length=250)
    description = models.TextField(max_length=250)
    age = models.IntegerField()

    toys = models.ManyToManyField(Toy)

    # ownership field (relationship to the user)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"bird_id": self.id})

    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >= len(MEALS)


class Feeding(models.Model):
    date = models.DateField("feeding date")
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ["-date"]


class Photo(models.Model):
    # store the url of image on aws
    url = models.CharField(max_length=200)
    # relationship to the cat
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cat id # {self.cat_id} @ {self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding


class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ["date", "meal"]

main_app/views.py
# package for generating unique keys for the photos
import uuid

# AWS SDK package
import boto3


from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# use sessions to log the user in
from django.contrib.auth import login

# display user inputs in a form
from django.contrib.auth.forms import UserCreationForm

# login required decorator
from django.contrib.auth.decorators import login_required

# login required mixin for class based view
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Bird, Toy, Photo
from .forms import FeedingForm

# format should be 'protocol://service-code.region-code.amazonaws.com'
S3_BASE_URL = "https://s3.us-east-2.amazonaws.com/"
BUCKET = "dareal-birdcollector"


def signup(request):
    error_message = ""

    if request.method == "POST":
        # Create the user using UserCreateForm
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # actually save the user if form data is valid
            user = form.save()
            # actually log the user in (session-based)
            login(request, user)
            return redirect("index")
        else:
            error_message = "Invalid data for sign up"

    # if a bad POST request, or a normal GET request, send errors to sign up template
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)


# from django.http import HttpResponse

# Create your views here.


def home(request):
    return render(request, "home.html")
    # return HttpResponse("<h1>Hello World</h1>")


def about(request):
    # return HttpResponse("<h1>About the Bird Collector</h1>")
    return render(request, "about.html")


@login_required
def birds_index(request):
    # Finds all the birds, regardless of user
    # birds = Bird.objects.all()

    # this filters to find only the birds owned by the logged in user
    birds = Bird.objects.filter(user=request.user)
    return render(request, "birds/index.html", {"birds": birds})


@login_required
def birds_detail(request, bird_id):
    bird = Bird.objects.get(id=bird_id)
    toys_bird_doesnt_have = Toy.objects.exclude(
        id__in=bird.toys.all().values_list("id")
    )
    feeding_form = FeedingForm()
    return render(
        request,
        "birds/detail.html",
        {"bird": bird, "feeding_form": feeding_form, "toys": toys_bird_doesnt_have},
    )


class BirdCreate(LoginRequiredMixin, CreateView):
    model = Bird
    # fields = "__all__"
    fields = ["name", "breed", "description", "age"]
    #  can redirect like below, but it's better to add a return in Model
    # success_url = "/birds/"
    # override form_valid to attach the user to the cat before form data is saved
    def form_valid(self, form):
        # the bird data will be stored in 'form.instance'
        # self.request.user will be the currently logged in user
        form.instance.user = self.request.user
        # allowing CreateView parent class to handle the rest
        return super().form_valid(form)


class BirdUpdate(LoginRequiredMixin, UpdateView):
    model = Bird
    fields = ["breed", "description", "age"]


class BirdDelete(LoginRequiredMixin, DeleteView):
    model = Bird
    success_url = "/birds/"


@login_required
def add_feeding(request, bird_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.bird_id = bird_id
        new_feeding.save()
    return redirect("detail", bird_id=bird_id)


@login_required
def toys_index(request):
    toys = Toy.objects.all()
    return render(request, "toys/index.html", {"toys": toys})


@login_required
def toys_detail(request, toy_id):
    toy = Toy.objects.get(id=toy_id)
    return render(request, "toys/detail.html", {"toy": toy})


class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = "__all__"


class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = "__all__"


class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = "/toys/"


@login_required
def assoc_toy(request, bird_id, toy_id):
    Bird.objects.get(id=bird_id).toys.add(toy_id)
    return redirect("detail", bird_id=bird_id)


# add @login_required when unassoc_toy is added
@login_required
def unassoc_toy(request, bird_id, toy_id):
    Bird.objects.get(id=bird_id).toys.remove(toy_id)
    return redirect("detail", bird_id=bird_id)


@login_required
def add_photo(request, bird_id):
    # the <input> will have 'name' attribute- that's the key our file will be on the incoming data
    photo_file = request.FILES.get("photo_file", None)

    if photo_file:
        # create an s3 instance
        s3 = boto3.client("s3")
        # generate a unique key for the image
        # variable to store index of the dot before the file extension
        # rfind will find the last instance of the '.' character
        index_of_last_period = photo_file.name.rfind(".")
        # generate a unique key and grab the first 6 characters of it
        # GEffed.png
        key = uuid.uuid4().hex[:6] + photo_file.name[index_of_last_period:]

        try:
            # s3 client - attempt to perform a file upload
            s3.upload_fileobj(photo_file, BUCKET, key)

            # generate the url based on the key name, our base url and bucket
            url = f"{S3_BASE_URL}{BUCKET}/{key}"

            photo = Photo(url=url, bird_id=bird_id)
            photo.save()
        except:
            print("An error occurred uploading files to AWS")

    # return redirect("bird", bird_id=bird_id)
    # return redirect("birds_detail", bird_id=bird_id)
    # return redirect("birds/detail.html", bird_id=bird_id)
    return redirect("detail", bird_id=bird_id)

main_app/templates/birds/detail.html
    {% extends 'base.html' %}
    {% block content %} 

    <!-- <h1>Bird Details</h1> -->
    <h1>{{ bird.name }}</h1>
    <hr>

    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ bird.name }}</span>
                    <p>Breed: {{ bird.breed }}</p>
                    <p>Description: {{ bird.description }}</p>
                    {% if bird.age > 0 %}
                    <p>Age: {{ bird.age }}</p>
                    {% else %}
                    <p>Age: {{bird.breed}}-ling</p>
                    {% endif %}
                </div>
                <div class="card-action">
                    <a href="{% url 'birds_update' bird.id %}">Edit</a>
                    <a href="{% url 'birds_delete' bird.id %}">Delete</a>
                </div>
            </div>

            <!-- display the bird photos -->
            {% for photo in bird.photo_set.all %}
                <img src="{{ photo.url }}" alt="{{ photo.url}}" class="responsive-img card-panel">
            {% empty %}
                <div class="card-panel indigo-text text-accent-2">No photos uploaded</div>

            {% endfor %}
            <!-- add photo form -->
            <form 
                action="{% url 'add_photo' bird.id %}" 
                enctype="multipart/form-data" 
                method="POST"
                class="card-panel">
                {% csrf_token %}

                <input type="file" name="photo_file">
                <br><br>
                <input type="submit" class="btn indigo accent-2" value="Upload Photo">
            </form>
        </div>
        <div class="col s6">
            <form action="{% url 'add_feeding' bird.id %}" method="post">
                {% csrf_token %}
                {{ feeding_form.as_p }}
                <input type="submit" class="btn indigo accent-2" value="Add Feeding">
            </form>
            <br>
            {% if bird.fed_for_today %}
                <div class="card-panel indigo-text text-accent-2 center-align">{{bird.name}} has been fed all meals for today</div>
            {% else %}
                <div class="card-panel red-text center-align">{{bird.name}} might be hungry...</div>
            {% endif %}

            <table class="striped">
                <thead>
                  <tr><th>Date</th><th>Meal</th></tr>
                </thead>
                <tbody>
                  {% for feeding in bird.feeding_set.all %}
                    <tr>
                      <td>{{feeding.date}}</td>
                      <td>{{feeding.get_meal_display}}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>

        </div>
    </div>  
    
    <hr>

    <div class="row">
        <div class="col s6">
            <h3>{{ bird.name }}'s Toys</h3>
        {% if bird.toys.count %}
            {% for toy in bird.toys.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'unassoc_toy' bird.id toy.id %}" method="post">
                            {% csrf_token %}
                          <button type="submit" class="btn indigo accent-2">Remove</button>
                        </form>
                    </div>
                </div>
            {% endfor%}
            {% else %}
                <h5>No Toys :(</h5>

        {% endif %}
        </div>
        <div class="col s6">
            <h3>Available Toys</h3>
            {%  if toys.count %}
                {% for toy in toys.all %}
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">
                                A<span style="color: {{toy.color}}"> {{ toy.color }} </span>{{ toy.name }}
                            </span>
                        </div>
                        <div class="card-action">
                            <form action="{% url 'assoc_toy' bird.id toy.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn indigo accent-2">Add</button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h5>{{bird.name}} Already has all toys available</h5>
            {%  endif %}

        </div>
    </div>
    <script>
        var dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });
        var selectEl = document.getElementById('id_meal');
        M.FormSelect.init(selectEl);
    </script>

    {% endblock %}

main_app/templates/birds/index.html
    {% extends 'base.html' %}
    {% block content %} 

    <h1>Bird List</h1>
    <hr>

    {% for bird in birds %}
    <a href="{% url 'detail' bird.id %}">
        <div class="card">
            <div class=" card-content">
                <span class="card-title">{{ bird.name }}</span>
                <!-- <p>Breed: {{ bird.breed }}</p> -->
                <!-- <p>Description: {{ bird.description }}</p>
                {% if bird.age > 0 %}
                    <p>Age: {{ bird.age }}</p>
                {% else %}
                    <p>Age: {{bird.breed}}-ling</p>
                {% endif %} -->
                <!-- {% for photo in bird.photo_set.all %}
                    <img src="{{ photo.url }}" alt="{{ photo.url}}" class="responsive-img card-panel">
                {% empty %}
                    <div class="card-panel indigo-text text-accent-2">No photos uploaded</div> -->

                <!-- {% endfor %}  -->
            </div>
        </div>
    </a>
    {% endfor %}

    {% endblock %}